name: create-dist
on:
  push:
    branches: [ "*" ]
  workflow_dispatch:
  workflow_call:

env:
  LOVE_VERSION: "11.4"

jobs:
  create-love-file:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload-artifact.outputs.artifact-id }}
      artifact-url: ${{ steps.upload-artifact.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - name: create game archive
        run: ./create_archive.sh
      - name: upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: game.love
          path: ./game.love

  create-windows-bundle:
    runs-on: ubuntu-latest
    needs: [ create-love-file ]
    steps:
      - name: download required windows files
        run: curl -sSL https://github.com/love2d/love/releases/download/${LOVE_VERSION}/love-${LOVE_VERSION}-win64.zip -o ./love-${LOVE_VERSION}-win64.zip
      - name: extract required windows files
        run: unzip ./love-${LOVE_VERSION}-win64.zip
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: game.love
          path: ./
      - name: create windows release
        run: |
          cp -r ./love-${LOVE_VERSION}-win64/ ./dist/
          cat ./dist/love.exe ./game.love > ./dist/game.exe
          rm ./dist/love.exe
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win64
          path: ./dist

  create-linux-bundle:
    runs-on: ubuntu-latest
    needs: [ create-love-file ]
    steps:
      - name: install appimagetool
        run: |
          sudo apt update
          sudo apt install -y fuse
          curl -sSL https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage -o /usr/local/bin/appimagetool
          chmod +x /usr/local/bin/appimagetool
      - name: download required linux file
        run: |
          curl -sSL https://github.com/love2d/love/releases/download/11.5/love-11.5-x86_64.AppImage -o ./love.AppImage
          chmod +x ./love.AppImage
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: game.love
          path: ./
      - name: create linux release
        run: |
          mkdir dist
          ./love.AppImage --appimage-extract
          cp ./game.love ./squashfs-root/game.love
          sed -i '/# uncomment and edit to add your own game/ a FUSE_PATH=$APPDIR/game.love' squashfs-root/AppRun
          appimagetool ./squashfs-root ./Game.AppImage
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./Game.AppImage

  create-web-bundle:
    runs-on: ubuntu-latest
    needs: [ create-love-file ]
    steps:
      - name: install love.js
        run: npm -g install love.js
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: game.love
          path: ./
      - name: create web release
        run: |
          love.js --compatibility --title "game" ./game.love ./dist/
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: ./dist
