name: format
on:
  push:
    branches: [ "*" ]

permissions:
  contents: write

jobs:
  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: python -m pip install pre-commit
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --show-diff-on-failure --color=always --all-files
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commmit_message: fix formatting
