name: release
on:
  release:
    types: [ "published", "created " ]

permissions:
  contents: write
  pages: write

jobs:
  create-artifacts:
    uses: ./.github/workflows/create_dist.yml

  attach-to-release:
    runs-on: ubuntu-latest
    needs: [ create-artifacts ]
    steps:
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: game.love
          path: ./
      - name: download windows files
        uses: actions/download-artifact@v4
        with:
          name: win64
          path: ./game-win64
      - name: package windows files
        run: zip -r ./game-win64.zip ./game-win64
      - name: download linux files
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: ./game-linux
      - name: upload game.love release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./game.love
            ./game-win64.zip
            ./game-linux/Game.AppImage

  update-github-pages:
    runs-on: ubuntu-latest
    needs: [ create-artifacts ]
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: upload github pages artifact
        id: upload-pages-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./web
      - name: deploy new pages version
        id: deploy-pages
        uses: actions/deploy-pages@v4
