name: release
on:
  release:
    types: [ "published", "created " ]

permissions:
  contents: write

jobs:
  create-artifacts:
    uses: ./.github/workflows/create_dist.yml

  attach-to-release:
    runs-on: ubuntu-latest
    needs: [ create-artifacts ]
    steps:
      - name: download love file
        uses: actions/download-artifact@v4
        with:
          name: game.love
          path: ./
      - name: download windows files
        uses: actions/download-artifact@v4
        with:
          name: win64
          path: ./game-win64
      - name: package windows files
        run: zip -r ./game-win64.zip ./game-win64
      - name: download linux files
        uses: actions/download-artifact@v4
        with:
          name: linux
          path: ./game-linux
      - name: upload game.love release asset
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./game.love
            ./game-win64.zip
            ./game-linux/Game.AppImage
